### ISSUE TITLE
service is None 

### ISSUE THREAD

**Issue by SmartManoj** [davidedelpapa/gphotospy#14]
#12 

04:15 ~/mysite/wa $ python3  p2.py                                                                                                                   
Traceback (most recent call last):
  File "p2.py", line 17, in <module>
    media_manager = Media(service)
  File "/home/egmore/.local/lib/python3.8/site-packages/gphotospy/media.py", line 487, in __init__
    self._service = service["service"]
TypeError: 'NoneType' object is not subscriptable
04:15 ~/mysite/wa $ cat gphtospy.log 
root - 2021-05-22 04:15:36,098 - ERROR - argument should be integer or bytes-like object, not 'str'

**Comment by SmartManoj** [comment]
https://github.com/davidedelpapa/gphotospy/blob/2268051fedd45c2a163d1302ade03bf84fdab2f6/gphotospy/authorize.py#L65

Is exception silently passed?

**Comment by SmartManoj** [comment]
Traceback (most recent call last):
  File "C:\Users\mkavi\AppData\Local\Programs\Python\Python39\lib\site-packages\gphotospy\authorize.py", line 60, in init
    service = build(service_name, version,  static_discovery=False, credentials=credentials)
  File "C:\Users\mkavi\AppData\Local\Programs\Python\Python39\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\mkavi\AppData\Local\Programs\Python\Python39\lib\site-packages\googleapiclient\discovery.py", line 299, in build
    service = build_from_document(
  File "C:\Users\mkavi\AppData\Local\Programs\Python\Python39\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\mkavi\AppData\Local\Programs\Python\Python39\lib\site-packages\googleapiclient\discovery.py", line 510, in build_from_document
    if isinstance(client_options, six.moves.collections_abc.Mapping):
AttributeError: module 'six.moves' has no attribute 'collections_abc'
Traceback (most recent call last):
  File "C:\Users\mkavi\Desktop\wa\p2.py", line 18, in <module>
    media_manager = Media(service)
  File "C:\Users\mkavi\AppData\Local\Programs\Python\Python39\lib\site-packages\gphotospy\media.py", line 487, in __init__
    self._service = service["service"]
TypeError: 'NoneType' object is not subscriptable
[Finished in 2.3s]

**Comment by SmartManoj** [comment]
Solved https://www.pythonanywhere.com/forums/topic/27344/
