### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'close'

### ISSUE THREAD

**Issue by SmartManoj** [davidedelpapa/gphotospy#17]
Server issue?
https://bugs.python.org/issue25037

```
Traceback (most recent call last):
File "/app/.heroku/python/lib/python3.9/http/client.py", line 519, in _read_next_chunk_size
return int(line, 16)
ValueError: invalid literal for int() with base 16: b'T{E\xe9\x9d\xc6Wi\x99\xc1\xc0\xea+_\xcf\xef\xbb\xa5\xb2\x9f-\x87\x94\xb7\xe0\x14\x98\xe6\x8e\xeez\x18Y\xf1\xd9\xd1\x99\x7f\xe1v.\xe6\x87J\x81h*,\x84\xc8\x90S\xdc4\xaf\x03\xdbfEk|\xc8]G\x9c6\xaa\xf3\
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/app/fi2.py", line 248, in photos
photos_list=p2.photo_kudu().items()
File "/app/p2.py", line 27, in photo_kudu
for first_media in media_iterator:
File "/app/gphotospy/media.py", line 782, in list
result = self._service.mediaItems().list(
File "/app/.heroku/python/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
return wrapped(*args, **kwargs)
File "/app/.heroku/python/lib/python3.9/site-packages/googleapiclient/http.py", line 920, in execute
resp, content = _retry_request(
File "/app/.heroku/python/lib/python3.9/site-packages/googleapiclient/http.py", line 191, in _retry_request
resp, content = http.request(uri, method, *args, **kwargs)
File "/app/.heroku/python/lib/python3.9/site-packages/google_auth_httplib2.py", line 218, in request
response, content = self.http.request(
File "/app/.heroku/python/lib/python3.9/site-packages/httplib2/__init__.py", line 1708, in request
(response, content) = self._request(
File "/app/.heroku/python/lib/python3.9/site-packages/httplib2/__init__.py", line 1424, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "/app/.heroku/python/lib/python3.9/site-packages/httplib2/__init__.py", line 1405, in _conn_request
content = response.read()
File "/app/.heroku/python/lib/python3.9/http/client.py", line 462, in read
return self._readall_chunked()
File "/app/.heroku/python/lib/python3.9/http/client.py", line 569, in _readall_chunked
chunk_left = self._get_chunk_left()
File "/app/.heroku/python/lib/python3.9/http/client.py", line 552, in _get_chunk_left
chunk_left = self._read_next_chunk_size()
File "/app/.heroku/python/lib/python3.9/http/client.py", line 523, in _read_next_chunk_size
self._close_conn()
File "/app/.heroku/python/lib/python3.9/http/client.py", line 409, in _close_conn
fp.close()
AttributeError: 'NoneType' object has no attribute 'close'
return int(line, 16)
ValueError: invalid literal for int() with base 16: b'T{E\xe9\x9d\xc6Wi\x99\xc1\xc0\xea+_\xcf\xef\xbb\xa5\xb2\x9f-\x87\x94\xb7\xe0\x14\x98\xe6\x8e\xeez\x18Y\xf1\xd9\xd1\x99\x7f\xe1v.\xe6\x87J\x81h*,\x84\xc8\x90S\xdc4\xaf\x03\xdbfEk|\xc8]G\x9c6\xaa\xf3\
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/app/fi2.py", line 248, in photos
photos_list=p2.photo_kudu().items()
File "/app/p2.py", line 27, in photo_kudu
for first_media in media_iterator:
File "/app/gphotospy/media.py", line 782, in list
result = self._service.mediaItems().list(
File "/app/.heroku/python/lib/python3.9/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
return wrapped(*args, **kwargs)
File "/app/.heroku/python/lib/python3.9/site-packages/googleapiclient/http.py", line 920, in execute
resp, content = _retry_request(
File "/app/.heroku/python/lib/python3.9/site-packages/googleapiclient/http.py", line 191, in _retry_request
resp, content = http.request(uri, method, *args, **kwargs)
File "/app/.heroku/python/lib/python3.9/site-packages/google_auth_httplib2.py", line 218, in request
response, content = self.http.request(
File "/app/.heroku/python/lib/python3.9/site-packages/httplib2/__init__.py", line 1708, in request
(response, content) = self._request(
File "/app/.heroku/python/lib/python3.9/site-packages/httplib2/__init__.py", line 1424, in _request
(response, content) = self._conn_request(conn, request_uri, method, body, headers)
File "/app/.heroku/python/lib/python3.9/site-packages/httplib2/__init__.py", line 1405, in _conn_request
content = response.read()
File "/app/.heroku/python/lib/python3.9/http/client.py", line 462, in read
return self._readall_chunked()
File "/app/.heroku/python/lib/python3.9/http/client.py", line 569, in _readall_chunked
chunk_left = self._get_chunk_left()
File "/app/.heroku/python/lib/python3.9/http/client.py", line 552, in _get_chunk_left
chunk_left = self._read_next_chunk_size()
File "/app/.heroku/python/lib/python3.9/http/client.py", line 523, in _read_next_chunk_size
self._close_conn()
File "/app/.heroku/python/lib/python3.9/http/client.py", line 409, in _close_conn
fp.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by SmartManoj** [comment]
https://twitter.com/SmartManoj42857/status/1441629179275931658
