### ISSUE TITLE
Request must have less than 50 items exception when trying to upload more then 50 images

### ISSUE THREAD

**Issue by alongouldman** [davidedelpapa/gphotospy#6]
when I try to stage more then 50 images, and then batchCreate, I get this: 

```
Traceback (most recent call last):
  File "/Users/alon/code/google_photos_uploader/uploader.py", line 114, in <module>
    main()
  File "/Users/alon/code/google_photos_uploader/uploader.py", line 110, in main
    upload_albums(selected_dirs)
  File "/Users/alon/code/google_photos_uploader/uploader.py", line 102, in upload_albums
    media_manager.batchCreate(album_id=id_album)
  File "/Users/alon/code/google_photos_uploader/google_photos_env/lib/python3.6/site-packages/gphotospy/media.py", line 697, in batchCreate
    body=request_body).execute()
  File "/Users/alon/code/google_photos_uploader/google_photos_env/lib/python3.6/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/Users/alon/code/google_photos_uploader/google_photos_env/lib/python3.6/site-packages/googleapiclient/http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://photoslibrary.googleapis.com/v1/mediaItems:batchCreate?alt=json returned "Request must have less than 50 items.">

```
it says [here](https://developers.google.com/photos/library/guides/access-media-items) that more then 50 in each request is not allowed. 
So maybe if  `len(self._staged_media) > 50` then it would split the request into a few pieces ?

(Im happy to fix it myself, let me know)

**Comment by davidedelpapa** [comment]
I'm happy to approve PR's 😁
Just before starting to work on this, let me review if we can unify with the work needed tor issue #5

**Comment by alongouldman** [comment]
so should I do both in the same PR?

**Comment by alongouldman** [comment]
PR: https://github.com/davidedelpapa/gphotospy/pull/7
(this is just the 50 items limit, not running the staging async... I will get to that another day :) )

**Comment by davidedelpapa** [comment]
> PR: #7
> (this is just the 50 items limit, not running the staging async... I will get to that another day :) )

Don't worry, I am trying to see how I can do that myelf. Thank you!
